config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notes

  authenticated :user do
    root 'notes#index', as: "authenticated_root"
  end

  get 'welcome/index'
  root 'welcome#index'
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]
  def index
    @notes = Note.where(user_id: current_user)
  end

  def show

  end

  def new
    @note = current_user.notes.build
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to @note
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private

  def find_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :content)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.haml
!!!
%html
%head
  %title E-Note
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = stylesheet_link_tag  ='https://fonts.googleapis.com/css?family=Raleway:400,700,300'
  = csrf_meta_tags

%body
  %header
    .header_inner
      = link_to "E-Note", root_path, id: "logo"
      %nav
        -if user_signed_in?
          = link_to "Nueva Nota", new_note_path
          = link_to "Cerrar Sesión", destroy_user_session_path, method: :delete
        - else
          = link_to "Iniciar Sesión", new_user_session_path

= yield

app/views/notes/_form.haml
= simple_form_for @note do |f|
  = f.input :title
  = f.input :content
  = f.button :submit, class: "button"

app/views/notes/edit.haml
.wrapper_with_padding
  %h1 Editando nota
  =render 'form'
  = link_to "Cancelar", note_path

app/views/notes/index.haml
.wrapper_with_padding
  #notes.clearfix
    -unless @notes.blank?
      -@notes.each do |note|
        %a{ href: (url_for [note])}
          .note
            %p.title= note.title
            %p.date= time_ago_in_words(note.created_at)
    -else
      %h2 Agregar nota
      %p Parece que no tienes notas :(
      %button= link_to "Nueva nota", new_note_path

app/views/notes/new.haml
.wrapper_with_padding
  %h1 Agregar una nota
  = render 'form'

app/views/notes/show.haml
.wrapper_with_padding
  #note_show
    %h1.title= @note.title
    %p= simple_format(@note.content)
    = link_to " Editar ", edit_note_path, class:"button"
    = link_to " Borrar ", note_path(@note), method: :delete, data: { confirm: "Estas seguro?"}, class:"button"

app/views/welcome/index.haml
#banner
  .banner_content
    %h1 E-note
    %p La mejor libreta online
    %button= link_to "Registrarse", new_user_registration_path
#testimonial
  .wrapper
    %p.quote "Semiotics cornhole flannel brooklyn, distillery tousled disrupt fap listicle knausgaard."
    %p.name - Pepito perez del fulano
#callouts
  .callout_inner
    .wrapper
      .callout
        %h2 Facil.
        %p Microdosing letterpress affogato chartreuse 8-bit, mixtape cray lomo.
      .callout
        %h2 Rapido.
        %p Microdosing letterpress affogato chartreuse 8-bit, mixtape cray lomo.
      .callout
        %h2 Gratis.
        %p Microdosing letterpress affogato chartreuse 8-bit, mixtape cray lomo.
#bottom_cta
  .wrapper
    %h2 Es gratis!!
    %p Registrate antes que empezemos a cobrar.
    %button= link_to "Click sobre mi", new_user_registration_path

%footer
  %p &copy; Kevin Rodríguez